<?php

/**
 * @file
 * Implement hook_datalayer_alter() and alter the Data Layer data before it is output to the screen.
 * Parameters: array $data_layer: GTM data layer data for the current page.
 */

function ubc_apsc_datalayer_datalayer_alter(&$data_layer) {
  
  if(isset($data_layer['entityType']) && $data_layer['entityType'] == 'node') {
	  
	  if(array_key_exists('entityTaxonomy', $data_layer)) {
	
		foreach($data_layer['entityTaxonomy'] as $taxonomy => $terms) {
			// include an additional CSV list of taxonomy terms in the datalayer
			$data_layer['entityTaxonomy'][$taxonomy]['list'] = implode(', ', $terms);
			
		}
	}
  }  
}

/**
 * Implements hook_update_projects_alter(&$projects).
 * Alter the list of projects before fetching data and comparing versions.
 *
 * Hide projects from the list to avoid "No available releases found" warnings on the available updates report
 *
 * @see \Drupal\update\UpdateManager::getProjects()
 * @see \Drupal\Core\Utility\ProjectInfo::processInfoList()
 */
function ubc_apsc_datalayer_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['ubc_apsc_syndicated_canonical_url']);
}
